-- Rank 1-10 SQL Data Entry
INSERT INTO Media (title, description, type, poster_image_link, score, status, aired_date, producer, studio, source, genre, duration) VALUES
('Sousou no Frieren', 'In a post-heroic age, the elven mage Frieren survives her companions and embarks on a journey to understand the brevity of human life and the depth of her past connections.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg', 9.3, 'completed', '2023-09-29', 'Aniplex, 'Madhouse', 'Manga', 'Adventure, Drama, Fantasy', '24 min'),
('Fullmetal Alchemist: Brotherhood', 'After a failed alchemical ritual leaves them physically scarred, the Elric brothers travel across a conspiracy-ridden nation to find the Philosopher''s Stone and restore their bodies.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1227/96253.jpg', 9.1, 'completed', '2009-04-05', 'Aniplex, Square Enix', 'Bones', 'Manga', 'Action, Adventure, Drama, Fantasy', '24 min'),
('Steins;Gate', 'A group of friends in Akihabara accidentally develop a method for sending text messages into the past, triggering a timeline-spanning war with a shadowy global organization.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg', 9.1, 'completed', '2011-04-06', 'Frontier Works', 'White Fox', 'Visual Novel', 'Drama, Sci-Fi, Suspense', '24 min'),
('Shingeki no Kyojin Season 3 Part 2', 'The struggle for survival reaches its peak as the Scout Regiment attempts to retake the Shiganshina District and uncover the secrets of the world hidden in a basement.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', 9.1, 'completed', '2019-04-29', 'Pony Canyon', 'Wit Studio', 'Manga', 'Action, Drama', '24 min'),
('Kingdom 6th Season', 'Xin and the state of Qin engage in monumental warfare during the Warring States period of ancient China, striving for the unprecedented unification of the land.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 9.1, 'airing', '2025-10-01', 'NHK', 'Studio Pierrot', 'Manga', 'Action, Historical', '24 min'),
('Gintama°', 'A collection of high-stakes arcs that shift the tone of the long-running series toward intense drama and the political collapse of alien-occupied Edo.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/3/72078.jpg', 9.1, 'completed', '2015-04-08', 'Aniplex', 'Bandai Namco Pictures', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Hunter x Hunter (2011)', 'Young Gon Freecss seeks to find his father by becoming a licensed Hunter, leading him into high-stakes battles and philosophical confrontations with monstrous beings.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', 9.0, 'completed', '2011-10-02', 'VAP', 'Madhouse', 'Manga', 'Action, Adventure, Fantasy', '24 min'),
('Ginga Eiyuu Densetsu', 'An epic military drama detailing the galactic struggle between the Galactic Empire and the Free Planets Alliance, focused on two brilliant strategic rivals.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/13/13225.jpg', 9.0, 'completed', '1988-01-08', 'Kitty Films', 'Artland', 'Novel', 'Drama, Sci-Fi', '26 min'),
('Gintama''', 'The Yorozuya continue their odd jobs in an Edo where traditional samurai values clash with extraterrestrial technology and urban gang politics.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 9.0, 'completed', '2011-04-04', 'TV Tokyo', 'Sunrise', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Gintama'': Enchousen', 'A series of additional episodes and reruns that dive deep into the corruption of the shogunate and the tragic history of the samurai resistance.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1452/123686.jpg', 9.0, 'completed', '2012-10-04', 'Aniplex', 'Sunrise', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('One Piece Fan Letter', 'A celebratory special that highlights the impact of the Straw Hat crew on the common people of the world, viewed from the ground up.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', 9.0, 'completed', '2024-10-20', 'Toei Animation', 'Toei Animation', 'Manga', 'Adventure, Fantasy', '24 min'),
('Bleach: Sennen Kessen-hen', 'Ichigo Kurosaki returns to the battlefield to defend the Soul Society against a terrifying invasion by the long-lost Quincy army.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1541/147774.jpg', 9.0, 'completed', '2022-10-11', 'TV Tokyo', 'Studio Pierrot', 'Manga', 'Action, Adventure, Supernatural', '24 min'),
('Gintama.', 'The Rakuyou Decisive Battle arc takes Gintoki to the stars to confront the origins of his immortal enemy and reunite his former comrades.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 9.0, 'completed', '2017-01-09', 'Aniplex', 'Bandai Namco Pictures', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Kaguya-sama wa Kokurasetai: Ultra Romantic', 'The intricate psychological warfare of the Shuchiin Academy student council reaches its romantic climax during a spectacular cultural festival.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1295/106551.jpg', 9.0, 'completed', '2022-04-09', 'Aniplex', 'A-1 Pictures', 'Manga', 'Comedy, Romance', '24 min'),
('Fruits Basket: The Final', 'The conclusion of the Sohma family saga, where Tohru Honda’s kindness finally threatens to break the century-old curse of the Chinese Zodiac.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1447/99827.jpg', 8.9, 'completed', '2021-04-06', 'TMS Entertainment', 'TMS Entertainment', 'Manga', 'Drama, Romance, Supernatural', '24 min'),
('Clannad: After Story', 'A profound exploration of family, grief, and the small miracles of life, following Tomoya as he navigates the hardships of adult existence.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1804/95033.jpg', 8.9, 'completed', '2008-10-03', 'Pony Canyon', 'Kyoto Animation', 'Visual Novel', 'Drama, Romance, Supernatural', '24 min'),
('Gintama', 'The foundational run of the series that established the legend of the silver-haired samurai and his dysfunctional odd-jobs team.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 8.9, 'completed', '2006-04-04', 'Sunrise', 'Sunrise', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Kusuriya no Hitorigoto 2nd Season', 'The apothecary Maomao continues to investigate mysterious illnesses and lethal conspiracies within the elaborate hierarchies of the Imperial Court.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1708/138033.jpg', 8.9, 'upcoming', '2025-01-10', 'TOHO animation', 'OLM', 'Light Novel', 'Drama, Mystery', '24 min'),
('Code Geass: Hangyaku no Lelouch R2', 'The exiled prince Lelouch escalates his global rebellion against the Britannian Empire, using the power of Geass to rewrite the fate of nations.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1032/135088.jpg', 8.9, 'completed', '2008-04-06', 'Bandai Entertainment', 'Sunrise', 'Original', 'Action, Drama, Sci-Fi', '24 min'),
('3-gatsu no Lion 2nd Season', 'Rei Kiriyama faces a new professional challenge in shogi while providing a safety net for his friends against the cruelty of school bullying.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/3/82899.jpg', 8.9, 'completed', '2017-10-14', 'Aniplex', 'Shaft', 'Manga', 'Drama, Slice of Life', '24 min'),
('Monster', 'Dr. Kenzo Tenma’s life is destroyed after he saves a young boy who grows into a charismatic sociopath, leading to a cross-continental game of cat and mouse.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/18793.jpg', 8.9, 'completed', '2004-04-07', 'VAP', 'Madhouse', 'Manga', 'Drama, Mystery, Suspense', '24 min'),
('Gintama. Shirogane no Tamashii-hen - Kouhan-sen', 'The final television confrontation as the citizens of Edo and the cosmic forces of the universe collide in a battle for existence.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 8.9, 'completed', '2018-07-09', 'Aniplex', 'Bandai Namco Pictures', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Shingeki no Kyojin: The Final Season - Kanketsu-hen', 'Eren Yeager begins the ultimate destruction of the world, forcing his former allies to make an impossible choice to save humanity.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', 8.9, 'completed', '2023-03-04', 'Pony Canyon', 'MAPPA', 'Manga', 'Action, Drama', '60 min'),
('Kusuriya no Hitorigoto', 'A girl with a passion for poisons becomes a low-ranking maid in the Imperial Palace, where her medical skills inadvertently make her a vital investigator.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1708/138033.jpg', 8.9, 'completed', '2023-10-22', 'TOHO animation', 'OLM', 'Light Novel', 'Drama, Mystery', '24 min'),
('Owarimonogatari 2nd Season', 'Koyomi Araragi faces the final specters of his high school life, seeking a resolution for the enigmatic Ougi Oshino and his own uncertain future.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/3/82899.jpg', 8.9, 'completed', '2017-08-12', 'Aniplex', 'Shaft', 'Light Novel', 'Mystery, Supernatural', '45 min'),
('Kingdom 3rd Season', 'The state of Qin is pushed to the brink of annihilation by a coalition of rival kingdoms, requiring a display of unparalleled military genius.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 8.8, 'completed', '2020-04-06', 'NHK', 'Studio Pierrot', 'Manga', 'Action, Historical', '24 min'),
('Boku no Hero Academia: Final Season', 'Deku and the students of Class 1-A engage in a definitive war against the League of Villains, determining the future of hero society.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 8.8, 'airing', '2025-10-01', 'Bones', 'Bones', 'Manga', 'Action, Super Power', '24 min'),
('Vinland Saga Season 2', 'Enslaved and hollowed out by his past sins, Thorfinn begins a painful journey toward peace and self-discovery on a remote farm.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1500/103005.jpg', 8.8, 'completed', '2023-01-10', 'Aniplex', 'MAPPA', 'Manga', 'Action, Adventure, Drama', '24 min'),
('Gintama. Shirogane no Tamashii-hen', 'The galactic invasion of Edo begins, testing the bonds of the Yorozuya and the resilience of the human spirit against overwhelming alien odds.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 8.8, 'completed', '2018-01-08', 'Aniplex', 'Bandai Namco Pictures', 'Manga', 'Action, Comedy, Sci-Fi', '24 min'),
('Takopii no Genzai', 'A well-meaning alien attempt to fix the life of a broken young girl leads to a cycle of psychological horror and tragic misunderstandings.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 8.8, 'completed', '2025-06-01', 'Cygames', 'MAPPA', 'Manga', 'Drama, Psychological', '15 min'),
('Shingeki no Kyojin: The Final Season', 'The perspective shifts to the nation of Marley, revealing the human cost of the Titan war and the morally gray motivations of its combatants.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', 8.8, 'completed', '2020-12-07', 'Pony Canyon', 'MAPPA', 'Manga', 'Action, Drama', '24 min'),
('Mob Psycho 100 II', 'Shigeo Kageyama balances the mundane struggles of middle school with psychic battles against an organization that seeks to use powers for global domination.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/73274.jpg', 8.8, 'completed', '2019-01-07', 'Warner Bros. Japan', 'Bones', 'Manga', 'Action, Comedy, Supernatural', '24 min'),
('Hajime no Ippo', 'Ippo Makunouchi transforms from a timid victim of bullying into a world-class boxer through discipline, mentorship, and sheer perseverance.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/4/86334.jpg', 8.8, 'completed', '2000-10-04', 'VAP', 'Madhouse', 'Manga', 'Action, Sports', '24 min'),
('Ashita no Joe 2', 'Joe Yabuki rises to the highest tier of professional boxing, culminating in a tragic and iconic pursuit of self-actualization in the ring.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/13/13225.jpg', 8.8, 'completed', '1980-10-13', 'TMS Entertainment', 'TMS Entertainment', 'Manga', 'Action, Sports', '24 min'),
('Haikyuu!! Karasuno vs. Shiratorizawa', 'The Karasuno High volleyball team faces their greatest challenge in a high-stakes match that serves as a masterpiece of sports tension and strategy.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/7/83326.jpg', 8.8, 'completed', '2016-10-08', 'Production I.G', 'Production I.G', 'Manga', 'Action, Sports', '24 min'),
('Shingeki no Kyojin: The Final Season Part 2', 'The activation of the Rumbling shatters the political landscape of Paradis, leading to the mobilization of the world’s final defenses.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', 8.8, 'completed', '2022-01-10', 'Pony Canyon', 'MAPPA', 'Manga', 'Action, Drama', '24 min'),
('Vinland Saga', 'Thorfinn spends his youth on the battlefield as a mercenary, driven by an all-consuming desire for revenge against the man who killed his father.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1500/103005.jpg', 8.8, 'completed', '2019-07-08', 'Twin Engine', 'Wit Studio', 'Manga', 'Action, Adventure, Drama', '24 min'),
('Monogatari Series: Second Season', 'A kaleidoscope of supernatural encounters involving a vampire, a ghost, and the complex psychological scars of a group of teenagers.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/3/82899.jpg', 8.8, 'completed', '2013-07-07', 'Aniplex', 'Shaft', 'Light Novel', 'Mystery, Supernatural', '24 min'),
('Cowboy Bebop', 'In a future where humanity has colonized the solar system, a group of bounty hunters drifts through space, unable to outrun their tragic pasts.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/4/19644.jpg', 8.8, 'completed', '1998-04-03', 'Sunrise', 'Sunrise', 'Original', 'Action, Sci-Fi', '24 min'),
('Bocchi the Rock!', 'Hitori Gotou attempts to overcome her paralyzing social anxiety by becoming a guitar hero and joining a local rock band.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg', 8.7, 'completed', '2022-10-09', 'Aniplex', 'CloverWorks', 'Manga', 'Comedy, Slice of Life', '24 min'),
('Kingdom 4th Season', 'King Ying Zheng struggles against political sabotage and betrayal within the royal court while Xin fights to secure the border states.', 'tvshow', 'https://cdn.myanimelist.net/images/anime/1160/122627.jpg', 8.7, 'completed', '2022-04-10', 'NHK', 'Studio Pierrot', 'Manga', 'Action, Historical', '24 min');


## Section 1: Top 10 Airing Anime


INSERT INTO Media (title, description, poster_link, score, status, aired_date, producer, studio, source, genre, duration) VALUES
('Kingdom 6th Season', 'The narrative of Qin unification of China continues as Xin and Zheng face new threats from the Zhao and Wei states.', 'https://cdn.myanimelist.net/images/anime/1355/140304.jpg', 9.04, 'Airing', 'Jan 2024', 'NHK', 'Pierrot', 'Manga', 'Action, Historical', '24 min'),
('Bleach: Sennen Kessen-hen - Kashin-tan', 'The final cour of the Thousand-Year Blood War arc where the fate of the Soul Society is decided against Yhwach.', 'https://cdn.myanimelist.net/images/anime/1063/145395.jpg', 9.05, 'Airing', 'Oct 2024', 'TV Tokyo', 'Pierrot', 'Manga', 'Action, Fantasy', '24 min'),
('Boku no Hero Academia: Final Season', 'Deku and the heroes of Class 1-A engage in the ultimate battle against All For One and Shigaraki.', 'https://cdn.myanimelist.net/images/anime/1841/142343.jpg', 8.85, 'Airing', 'May 2024', 'Shueisha', 'Bones', 'Manga', 'Action, Super Power', '23 min'),
('One Piece', 'Monkey D. Luffy and his Straw Hat crew continue their journey in the Egghead Island arc to find the legendary treasure.', 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', 8.75, 'Airing', 'Oct 1999', 'Fuji TV', 'Toei Animation', 'Manga', 'Action, Adventure', '24 min'),
('Uma Musume: Cinderella Gray Part 2', 'A focus on Oguri Cap as she moves to the central racing league to face even more formidable horse girl opponents.', 'https://cdn.myanimelist.net/images/anime/1484/144673.jpg', 8.64, 'Airing', 'Oct 2024', 'Cygames', 'Science SARU', 'Manga', 'Sports, Racing', '24 min'),
('Fumetsu no Anata e Season 3', 'The immortal entity Fushi navigates the complexities of the modern era after centuries of observation.', 'https://cdn.myanimelist.net/images/anime/1897/129758.jpg', 8.45, 'Airing', 'Oct 2024', 'NHK', 'Drive', 'Manga', 'Adventure, Supernatural', '24 min'),
('Blue Lock: Vs. U-20 Japan', 'The final selection for the egoist strikers as they face the official Japanese national youth team for survival.', 'https://cdn.myanimelist.net/images/anime/1183/145450.jpg', 8.35, 'Airing', 'Oct 2024', 'Bandai Namco', '8bit', 'Manga', 'Sports, Shounen', '24 min'),
('Chiikawa', 'Small, cute creatures live daily lives filled with mystery, lightheartedness, and occasional existential dread.', 'https://cdn.myanimelist.net/images/anime/1033/121118.jpg', 8.20, 'Airing', 'Apr 2022', 'Kodansha', 'Doga Kobo', 'Manga', 'Slice of Life, Comedy', '1 min'),
('Shuumatsu no Walküre III', 'Gods and humans continue their 13-round duel for the survival of humanity in the arena of Valhalla.', 'https://cdn.myanimelist.net/images/anime/1966/133038.jpg', 8.12, 'Airing', '2024', 'Warner Bros', 'Graphinica', 'Manga', 'Action, Drama', '24 min'),
('Nageki no Bourei wa Intai shitai Part 2', 'Krai continues his unintentional climb to legendary hero status while desperately trying to quit.', 'https://cdn.myanimelist.net/images/anime/1049/145464.jpg', 7.95, 'Airing', 'Oct 2024', 'Micro Magazine', 'Unknown', 'Light Novel', 'Adventure, Fantasy', '23 min');



## Section 2: Top 20 Upcoming Anime

INSERT INTO Media (title, description, poster_link, score, status, aired_date, producer, studio, source, genre, duration) VALUES
('Sousou no Frieren 2nd Season', 'The second season following Frieren journey to the northern lands of Aureole.', 'https://cdn.myanimelist.net/images/anime/1015/138024.jpg', NULL, 'Upcoming', 'Jan 2026', 'Aniplex', 'Madhouse', 'Manga', 'Adventure, Fantasy', '24 min'),
('Jigokuraku 2nd Season', 'Gabimaru and the survivors of the initial island expedition venture deeper into the mystery of the Elixir.', 'https://cdn.myanimelist.net/images/anime/1510/135987.jpg', NULL, 'Upcoming', 'Jan 2026', 'Twin Engine', 'MAPPA', 'Manga', 'Action, Adventure', '24 min'),
('Youjo Senki II', 'Tanya Degurechaff returns to lead the Imperial 203rd Aerial Mage Battalion into another global conflict.', 'https://cdn.myanimelist.net/images/anime/1188/115591.jpg', NULL, 'Upcoming', '2026', 'Kadokawa', 'Nut', 'Light Novel', 'Isekai, Military', '24 min'),
('Jujutsu Kaisen: Shimetsu Kaiyuu', 'The Culling Game arc begins as Kenjaku initiates a ritual that forces sorcerers and civilians into a deadly game.', 'https://cdn.myanimelist.net/images/anime/1739/140226.jpg', NULL, 'Upcoming', 'Jan 2026', 'TOHO', 'MAPPA', 'Manga', 'Action, Supernatural', '24 min'),
('Mushoku Tensei III', 'Rudeus Greyrat enters adulthood and faces the challenges of protecting his family and legacy.', 'https://cdn.myanimelist.net/images/anime/1051/144186.jpg', NULL, 'Upcoming', '2026', 'Egg Firm', 'Studio Bind', 'Light Novel', 'Isekai, Adventure', '24 min'),
('[Oshi no Ko] 3rd Season', 'Aqua and Ruby continue their revenge plot within the heart of the Japanese idol and acting industry.', 'https://cdn.myanimelist.net/images/anime/1915/145558.jpg', NULL, 'Upcoming', 'Jan 2026', 'Kadokawa', 'Doga Kobo', 'Manga', 'Drama, Supernatural', '24 min'),
('Kage no Jitsuryokusha ni Naritakute! Movie', 'Cid Kagenou takes his shadow persona to the cinematic screen to fight a global conspiracy.', 'https://cdn.myanimelist.net/images/anime/1665/140889.jpg', NULL, 'Upcoming', '2026', 'Kadokawa', 'Nexus', 'Light Novel', 'Action, Fantasy', '90 min'),
('Dungeon Meshi 2nd Season', 'The party continues their trek into the lower depths of the dungeon to rescue Falin.', 'https://cdn.myanimelist.net/images/anime/1376/143521.jpg', NULL, 'Upcoming', 'TBA', 'Kadokawa', 'Trigger', 'Manga', 'Adventure, Gourmet', '24 min'),
('Re:Zero kara Hajimeru Isekai Seikatsu 4th Season', 'Subaru faces the aftermath of the Sanctuary and heads toward a new conflict with the Witch Cult.', 'https://cdn.myanimelist.net/images/anime/1209/141703.jpg', NULL, 'Upcoming', 'Apr 2026', 'Kadokawa', 'White Fox', 'Light Novel', 'Isekai, Drama', '24 min'),
('Bocchi the Rock! 2nd Season', 'Hitori Gotoh continues to overcome her social anxiety through music and friendship in the Kessoku Band.', 'https://cdn.myanimelist.net/images/anime/1448/127956.jpg', NULL, 'Upcoming', 'TBA', 'Aniplex', 'CloverWorks', 'Manga', 'Comedy, Music', '24 min'),
('Tensei shitara Slime Datta Ken 4th Season', 'Rimuru Tempest leads his nation of monsters into an era of diplomatic and military expansion.', 'https://cdn.myanimelist.net/images/anime/1351/143574.jpg', NULL, 'Upcoming', 'Apr 2026', 'Bandai Namco', '8bit', 'Light Novel', 'Isekai, Fantasy', '24 min'),
('Enen no Shouboutai: San no Shou Part 2', 'The Special Fire Force Unit 8 battles the Evangelist for the fate of Tokyo.', 'https://cdn.myanimelist.net/images/anime/1314/144577.jpg', NULL, 'Upcoming', 'Jan 2026', 'Funimation', 'David Production', 'Manga', 'Action, Sci-Fi', '24 min'),
('Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season', 'Kiyotaka Ayanokouji begins his second year at the elite Advanced Nurturing High School.', 'https://cdn.myanimelist.net/images/anime/1020/145155.jpg', NULL, 'Upcoming', 'Apr 2026', 'Kadokawa', 'Lerche', 'Light Novel', 'Drama, Suspense', '24 min'),
('Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san S2', 'Alya and Masachika relationship deepens during their second year of high school.', 'https://cdn.myanimelist.net/images/anime/1917/145612.jpg', NULL, 'Upcoming', '2026', 'Kadokawa', 'Doga Kobo', 'Light Novel', 'Comedy, Romance', '24 min'),
('Dandadan 3rd Season', 'Momo and Okarun continue their quest to retrieve Okarun kintama while fighting aliens and spirits.', 'https://cdn.myanimelist.net/images/anime/1131/140131.jpg', NULL, 'Upcoming', 'TBA', 'Aniplex', 'Science SARU', 'Manga', 'Supernatural, Action', '24 min'),
('The World Finest Assassin S2', 'Lugh Tuatha Dé mission to kill the hero takes a turn as new political players emerge.', 'https://cdn.myanimelist.net/images/anime/1963/119047.jpg', NULL, 'Upcoming', 'TBA', 'Crunchyroll', 'Silver Link', 'Light Novel', 'Isekai, Action', '24 min'),
('Fate/strange Fake', 'A fake Holy Grail War in Snowfield, USA, summons heroes of legendary and modern status.', 'https://cdn.myanimelist.net/images/anime/1865/133550.jpg', NULL, 'Upcoming', 'Jan 2026', 'Aniplex', 'A-1 Pictures', 'Light Novel', 'Action, Fantasy', '24 min'),
('Tensei shitara Ken deshita 2', 'Fran and her sentient sword, Teacher, travel to a new continent to gain more power.', 'https://cdn.myanimelist.net/images/anime/1359/129759.jpg', NULL, 'Upcoming', 'Oct 2026', 'NBCUniversal', 'C2C', 'Light Novel', 'Isekai, Action', '24 min'),
('Mahou Shoujo Madoka★Magica Movie 4', 'Homura Akemi faces the consequences of the law of cycles in a world where she is god.', 'https://cdn.myanimelist.net/images/anime/1884/137684.jpg', NULL, 'Upcoming', 'Feb 2026', 'Aniplex', 'Shaft', 'Original', 'Drama, Psychological', '120 min'),
('Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken 2', 'Amane and Mahiru continue their wholesome domestic life together.', 'https://cdn.myanimelist.net/images/anime/1205/138139.jpg', NULL, 'Upcoming', 'Apr 2026', 'TOHO', 'project No.9', 'Light Novel', 'Romance, School', '24 min');


## 
## Section 3: Top 20 Movie Anime

INSERT INTO Media (title, description, poster_link, score, status, aired_date, producer, studio, source, genre, duration) VALUES
('Chainsaw Man Movie: Reze-hen', 'Denji encounters a girl named Reze who leads him into the explosive Bomb Girl arc.', 'https://cdn.myanimelist.net/images/anime/1065/140307.jpg', 9.15, 'Finished', 'Sep 2025', 'Crunchyroll', 'MAPPA', 'Manga', 'Action, Supernatural', '90 min'),
('Gintama: The Final', 'The Yorozuya reunites for one last battle against Utsuro to save Earth and their teacher.', 'https://cdn.myanimelist.net/images/anime/1245/116760.jpg', 9.05, 'Finished', 'Jan 2021', 'Warner Bros', 'Bandai Namco Pictures', 'Manga', 'Action, Comedy', '104 min'),
('Koe no Katachi', 'A young man tries to make amends with a deaf girl he bullied in elementary school.', 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg', 8.93, 'Finished', 'Sep 2016', 'ABC Animation', 'Kyoto Animation', 'Manga', 'Drama, School', '130 min'),
('Gintama Movie 2: Kanketsu-hen', 'Gintoki is transported five years into the future where a virus has decimated the population.', 'https://cdn.myanimelist.net/images/anime/10/50647.jpg', 8.89, 'Finished', 'Jul 2013', 'Aniplex', 'Sunrise', 'Manga', 'Action, Comedy', '110 min'),
('Violet Evergarden Movie', 'Violet continues her search for the meaning of "I love you" as she looks for Major Gilbert.', 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg', 8.84, 'Finished', 'Sep 2020', 'ABC Animation', 'Kyoto Animation', 'Light Novel', 'Drama, Slice of Life', '140 min'),
('Shingeki no Kyojin Movie: Kanketsu-hen', 'The cinematic presentation of the final episodes including the Rumbling and the final clash.', 'https://cdn.myanimelist.net/images/anime/1279/131078.jpg', 8.83, 'Finished', 'Nov 2024', 'Pony Canyon', 'MAPPA', 'Manga', 'Action, Drama', '145 min'),
('Kimi no Na wa.', 'Two high school students from different backgrounds swap bodies and embark on a search for one another.', 'https://cdn.myanimelist.net/images/anime/5/87048.jpg', 8.83, 'Finished', 'Aug 2016', 'Toho', 'Comix Wave Films', 'Original', 'Romance, Supernatural', '106 min'),
('Kizumonogatari III: Reiketsu-hen', 'Koyomi Araragi faces the final challenge to regain his humanity after his vampire conversion.', 'https://cdn.myanimelist.net/images/anime/12/82890.jpg', 8.78, 'Finished', 'Jan 2017', 'Aniplex', 'Shaft', 'Light Novel', 'Mystery, Supernatural', '83 min'),
('Sen to Chihiro no Kamikakushi', 'A young girl wanders into a spirit realm and must work in a bathhouse to free her parents.', 'https://cdn.myanimelist.net/images/anime/6/79597.jpg', 8.77, 'Finished', 'Jul 2001', 'Toho', 'Studio Ghibli', 'Original', 'Adventure, Supernatural', '125 min'),
('Kaguya-sama wa Kokurasetai: First Kiss', 'The student council faces the romantic tension following their legendary festival confession.', 'https://cdn.myanimelist.net/images/anime/1045/129189.jpg', 8.72, 'Finished', 'Dec 2022', 'Aniplex', 'A-1 Pictures', 'Manga', 'Romance, Comedy', '96 min'),
('The First Slam Dunk', 'Shohoku High basketball team faces Sannoh Industrial in a high-stakes championship game.', 'https://cdn.myanimelist.net/images/anime/1795/129337.jpg', 8.71, 'Finished', 'Dec 2022', 'Toei Animation', 'Toei Animation', 'Manga', 'Sports, Drama', '124 min'),
('Kimetsu no Yaiba Movie: Akaza Sairai', 'The Infinity Castle arc begins with the rematch between Tanjiro and the Upper Moon 3 demon Akaza.', 'https://cdn.myanimelist.net/images/anime/1735/143578.jpg', 8.70, 'Finished', 'Jul 2025', 'Aniplex', 'ufotable', 'Manga', 'Action, Fantasy', '115 min'),
('Howl no Ugoku Shiro', 'A young milliner is cursed with an old body and seeks help from a wizard in his moving castle.', 'https://cdn.myanimelist.net/images/anime/1540/144574.jpg', 8.67, 'Finished', 'Nov 2004', 'Toho', 'Studio Ghibli', 'Novel', 'Adventure, Fantasy', '119 min'),
('Mononoke Hime', 'A young prince is caught in a war between forest spirits and a mining colony.', 'https://cdn.myanimelist.net/images/anime/7/75919.jpg', 8.67, 'Finished', 'Jul 1997', 'Toho', 'Studio Ghibli', 'Original', 'Action, Adventure', '133 min'),
('Uma Musume: Pretty Derby - Shin Jidai', 'A new generation of horse girls competes for the title of the fastest in the central league.', 'https://cdn.myanimelist.net/images/anime/1519/140682.jpg', 8.64, 'Finished', 'May 2024', 'Cygames', 'CygamesPictures', 'Manga', 'Sports, Racing', '108 min'),
('Fate/stay night Movie: Heaven’s Feel III', 'The dark truth of the Holy Grail War is revealed as Shirou and Sakura face their destiny.', 'https://cdn.myanimelist.net/images/anime/1202/107530.jpg', 8.64, 'Finished', 'Aug 2020', 'Aniplex', 'ufotable', 'Visual Novel', 'Action, Fantasy', '122 min'),
('Look Back', 'Two young girls are bonded together by their shared passion for creating manga.', 'https://cdn.myanimelist.net/images/anime/1183/141870.jpg', 8.63, 'Finished', 'Jun 2024', 'Avex Pictures', 'Studio Durian', 'Manga', 'Drama, Slice of Life', '58 min'),
('Haikyuu!! Movie: Gomisuteba no Kessen', 'The fated "Trashcan Battle" between Karasuno and Nekoma finally takes place at the Nationals.', 'https://cdn.myanimelist.net/images/anime/1911/140924.jpg', 8.61, 'Finished', 'Feb 2024', 'TOHO', 'Production I.G', 'Manga', 'Sports, Shounen', '85 min'),
('Made in Abyss Movie 3', 'Riko, Reg, and Nanachi descend into the fifth layer to face the sovereign Bondrewd.', 'https://cdn.myanimelist.net/images/anime/1848/104523.jpg', 8.60, 'Finished', 'Jan 2020', 'Kadokawa', 'Kinema Citrus', 'Manga', 'Adventure, Drama', '105 min'),
('Tengen Toppa Gurren Lagann Movie 2', 'Simon and Team Dai-Gurren face the Anti-Spiral in the ultimate universal-scale showdown.', 'https://cdn.myanimelist.net/images/anime/1126/133036.jpg', 8.60, 'Finished', 'Apr 2009', 'Aniplex', 'Gainax', 'Original', 'Action, Sci-Fi', '126 min');


## Section 4: Top 30 Manga

INSERT INTO Media (title, description, poster_link, score, status, aired_date, producer, studio, source, genre, duration) VALUES
('Berserk', 'Guts, a mercenary, seeks revenge against Griffith in a world overrun by demons.', 'https://cdn.myanimelist.net/images/manga/1/157897.jpg', 9.47, 'Finished', 'Aug 1989', 'Hakusensha', 'N/A', 'Manga', 'Seinen, Fantasy', '41 Vol'),
('JoJo no Kimyou na Bouken Part 7: Steel Ball Run', 'Johnny Joestar and Gyro Zeppeli participate in a cross-country horse race across 1890s America.', 'https://cdn.myanimelist.net/images/manga/3/179882.jpg', 9.33, 'Finished', 'Jan 2004', 'Shueisha', 'N/A', 'Manga', 'Seinen, Adventure', '24 Vol'),
('Vagabond', 'The fictionalized life of the legendary Japanese swordmaster Miyamoto Musashi.', 'https://cdn.myanimelist.net/images/manga/1/25960.jpg', 9.27, 'Publishing', 'Sep 1998', 'Kodansha', 'N/A', 'Manga', 'Seinen, Samurai', '37 Vol'),
('One Piece', 'Monkey D. Luffy leads his pirate crew in search of the legendary One Piece treasure.', 'https://cdn.myanimelist.net/images/manga/2/253146.jpg', 9.22, 'Publishing', 'Jul 1997', 'Shueisha', 'N/A', 'Manga', 'Shounen, Adventure', '108 Vol'),
('Monster', 'Dr. Kenzo Tenma tracks down a young man whose life he saved who has become a serial killer.', 'https://cdn.myanimelist.net/images/manga/3/258224.jpg', 9.16, 'Finished', 'Dec 1994', 'Shogakukan', 'N/A', 'Manga', 'Seinen, Thriller', '18 Vol'),
('Guimi Zhi Zhu', 'A transmigrated man finds himself in a Victorian-style world with steampunk and occult elements.', 'https://cdn.myanimelist.net/images/manga/3/231145.jpg', 9.16, 'Finished', '2018', 'Qidian', 'N/A', 'Novel', 'Mystery, Steampunk', '8 Vol'),
('Vinland Saga', 'Thorfinn seeks to reach the mythical Vinland while navigating the violence of the Viking age.', 'https://cdn.myanimelist.net/images/manga/2/188925.jpg', 9.09, 'Publishing', 'Apr 2005', 'Kodansha', 'N/A', 'Manga', 'Seinen, Historical', '27 Vol'),
('Slam Dunk', 'Hanamichi Sakuragi joins the Shohoku basketball team to impress a girl but discovers a love for the game.', 'https://cdn.myanimelist.net/images/manga/2/258749.jpg', 9.08, 'Finished', 'Sep 1990', 'Shueisha', 'N/A', 'Manga', 'Shounen, Sports', '31 Vol'),
('Fullmetal Alchemist', 'Edward and Alphonse Elric search for the Philosopher Stone to restore their bodies.', 'https://cdn.myanimelist.net/images/manga/3/243675.jpg', 9.04, 'Finished', 'Jul 2001', 'Square Enix', 'N/A', 'Manga', 'Shounen, Adventure', '27 Vol'),
('Omniscient Reader’s Viewpoint', 'A man finds himself living in the world of a novel he spent ten years reading.', 'https://cdn.myanimelist.net/images/manga/2/231131.jpg', 9.04, 'Publishing', '2018', 'Munpia', 'N/A', 'Novel', 'Action, Isekai', '5 Vol'),
('Grand Blue', 'Iori Kitahara moves to a coastal town and joins a diving club filled with rowdy upperclassmen.', 'https://cdn.myanimelist.net/images/manga/2/166124.jpg', 9.04, 'Publishing', 'Apr 2014', 'Kodansha', 'N/A', 'Manga', 'Seinen, Comedy', '21 Vol'),
('Tian Guan Cifu', 'Xie Lian, a banished god, returns to the heavenly realm and uncovers ancient secrets.', 'https://cdn.myanimelist.net/images/manga/2/236712.jpg', 9.02, 'Finished', '2017', 'Jinjiang', 'N/A', 'Novel', 'Fantasy, Historical', '8 Vol'),
('The Greatest Estate Developer', 'An engineer is reincarnated in a fantasy novel and must save a failing noble family with construction.', 'https://cdn.myanimelist.net/images/manga/1/257321.jpg', 9.02, 'Publishing', '2021', 'Naver', 'N/A', 'Manhwa', 'Fantasy, Comedy', '1 Vol'),
('Kingdom', 'The story of Xin and his climb from orphan to great general during the warring states era.', 'https://cdn.myanimelist.net/images/manga/2/171872.jpg', 9.02, 'Publishing', 'Jan 2006', 'Shueisha', 'N/A', 'Manga', 'Seinen, Historical', '70 Vol'),
('Oyasumi Punpun', 'The coming-of-age story of a boy named Punpun through the dark realities of life.', 'https://cdn.myanimelist.net/images/manga/3/164420.jpg', 8.98, 'Finished', 'Mar 2007', 'Shogakukan', 'N/A', 'Manga', 'Seinen, Psychological', '13 Vol'),
('Houseki no Kuni', 'Gem-based lifeforms live in a far-future world where they fight beings from the moon.', 'https://cdn.myanimelist.net/images/manga/1/134805.jpg', 8.98, 'Finished', 'Oct 2012', 'Kodansha', 'N/A', 'Manga', 'Seinen, Sci-Fi', '12 Vol'),
('Real', 'A story of three young men whose lives are changed through wheelchair basketball.', 'https://cdn.myanimelist.net/images/manga/2/115969.jpg', 8.96, 'Publishing', 'Oct 1999', 'Shueisha', 'N/A', 'Manga', 'Seinen, Sports', '15 Vol'),
('Ashita no Joe', 'A runaway boy finds a sense of belonging and purpose through the world of boxing.', 'https://cdn.myanimelist.net/images/manga/1/26888.jpg', 8.94, 'Finished', 'Jan 1968', 'Kodansha', 'N/A', 'Manga', 'Shounen, Sports', '20 Vol'),
('20th Century Boys', 'Kenji and his friends must stop a cult from destroying the world using their childhood plans.', 'https://cdn.myanimelist.net/images/manga/2/258225.jpg', 8.93, 'Finished', 'Sep 1999', 'Shogakukan', 'N/A', 'Manga', 'Seinen, Mystery', '22 Vol'),
('Umineko no Naku Koro ni Chiru - Ep 8', 'The final confrontation between Battler and Beatrice to find the truth of the Rokkenjima murders.', 'https://cdn.myanimelist.net/images/manga/3/118381.jpg', 8.92, 'Finished', 'Dec 2011', 'Square Enix', 'N/A', 'Manga', 'Mystery, Horror', '9 Vol'),
('Yotsuba to!', 'The innocent daily life of a green-haired five-year-old girl and her adopted father.', 'https://cdn.myanimelist.net/images/manga/3/57369.jpg', 8.91, 'Publishing', 'Mar 2003', 'Kadokawa', 'N/A', 'Manga', 'Shounen, Slice of Life', '15 Vol'),
('Monogatari Series: First Season', 'Koyomi Araragi helps various girls with supernatural problems called "oddities."', 'https://cdn.myanimelist.net/images/manga/2/173954.jpg', 8.91, 'Finished', 'Nov 2006', 'Kodansha', 'N/A', 'Novel', 'Mystery, Supernatural', '6 Vol'),
('Monogatari Series: Second Season', 'The narrative shifts to the perspectives of the girls as they deal with their own supernatural burdens.', 'https://cdn.myanimelist.net/images/manga/2/173955.jpg', 8.90, 'Finished', 'Sep 2010', 'Kodansha', 'N/A', 'Novel', 'Mystery, Supernatural', '6 Vol'),
('Kaguya-sama wa Kokurasetai', 'Two genius high school students wage war to make the other confess their love first.', 'https://cdn.myanimelist.net/images/manga/3/188896.jpg', 8.89, 'Finished', 'May 2015', 'Shueisha', 'N/A', 'Manga', 'Seinen, Romance', '28 Vol'),
('Mo Dao Zu Shi', 'The Grandmaster of Demonic Cultivation is reincarnated and must solve a mystery from his past.', 'https://cdn.myanimelist.net/images/manga/2/236710.jpg', 8.89, 'Finished', 'Oct 2015', 'Jinjiang', 'N/A', 'Novel', 'Action, Supernatural', '4 Vol'),
('Mikkakan no Koufuku', 'A man sells his remaining years of life for a sum of money and finds unexpected love.', 'https://cdn.myanimelist.net/images/manga/2/183130.jpg', 8.88, 'Finished', 'Dec 2013', 'Media Factory', 'N/A', 'Novel', 'Drama, Romance', '1 Vol'),
('Sousou no Frieren', 'An elf mage explores the meaning of time and humanity after her hero party dies.', 'https://cdn.myanimelist.net/images/manga/3/232133.jpg', 8.86, 'Publishing', 'Apr 2020', 'Shogakukan', 'N/A', 'Manga', 'Shounen, Fantasy', '12 Vol'),
('Haikyuu!!', 'Shoyo Hinata overcomes his short stature to become a volleyball ace at Karasuno High.', 'https://cdn.myanimelist.net/images/manga/2/258229.jpg', 8.86, 'Finished', 'Feb 2012', 'Shueisha', 'N/A', 'Manga', 'Shounen, Sports', '45 Vol'),
('GTO', 'Former gang leader Eikichi Onizuka becomes a teacher to provide guidance to troubled students.', 'https://cdn.myanimelist.net/images/manga/2/258741.jpg', 8.86, 'Finished', 'Dec 1996', 'Kodansha', 'N/A', 'Manga', 'Shounen, Comedy', '25 Vol'),
('3-gatsu no Lion', 'A professional shogi player finds family and emotional stability through a group of three sisters.', 'https://cdn.myanimelist.net/images/manga/2/115167.jpg', 8.85, 'Publishing', 'Jul 2007', 'Hakusensha', 'N/A', 'Manga', 'Seinen, Drama', '17 Vol');